/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/tracepoint.proto */

#ifndef PROTOBUF_C_proto_2ftracepoint_2eproto__INCLUDED
#define PROTOBUF_C_proto_2ftracepoint_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Tracepoint Tracepoint;


/* --- enums --- */


/* --- messages --- */

struct  Tracepoint
{
  ProtobufCMessage base;
  char *tracepoint_text;
  char *service_name;
  uint64_t curr_time;
};
#define TRACEPOINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tracepoint__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/* Tracepoint methods */
void   tracepoint__init
                     (Tracepoint         *message);
size_t tracepoint__get_packed_size
                     (const Tracepoint   *message);
size_t tracepoint__pack
                     (const Tracepoint   *message,
                      uint8_t             *out);
size_t tracepoint__pack_to_buffer
                     (const Tracepoint   *message,
                      ProtobufCBuffer     *buffer);
Tracepoint *
       tracepoint__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tracepoint__free_unpacked
                     (Tracepoint *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Tracepoint_Closure)
                 (const Tracepoint *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tracepoint__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2ftracepoint_2eproto__INCLUDED */
