/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tracepoint.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tracepoint.pb-c.h"
void   tracepoint__init
                     (Tracepoint         *message)
{
  static const Tracepoint init_value = TRACEPOINT__INIT;
  *message = init_value;
}
size_t tracepoint__get_packed_size
                     (const Tracepoint *message)
{
  assert(message->base.descriptor == &tracepoint__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tracepoint__pack
                     (const Tracepoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tracepoint__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tracepoint__pack_to_buffer
                     (const Tracepoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tracepoint__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tracepoint *
       tracepoint__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tracepoint *)
     protobuf_c_message_unpack (&tracepoint__descriptor,
                                allocator, len, data);
}
void   tracepoint__free_unpacked
                     (Tracepoint *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tracepoint__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tracepoint__field_descriptors[3] =
{
  {
    "tracepoint_text",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tracepoint, tracepoint_text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tracepoint, service_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curr_time",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Tracepoint, curr_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tracepoint__field_indices_by_name[] = {
  2,   /* field[2] = curr_time */
  1,   /* field[1] = service_name */
  0,   /* field[0] = tracepoint_text */
};
static const ProtobufCIntRange tracepoint__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tracepoint__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Tracepoint",
  "Tracepoint",
  "Tracepoint",
  "",
  sizeof(Tracepoint),
  3,
  tracepoint__field_descriptors,
  tracepoint__field_indices_by_name,
  1,  tracepoint__number_ranges,
  (ProtobufCMessageInit) tracepoint__init,
  NULL,NULL,NULL    /* reserved[123] */
};
